# Generated by Django 3.0.3 on 2020-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200728_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(choices=[('IMAGES/profile_pics/no_profile_pic.jpg', 'No Image'), ('IMAGES/profile_pics/avatar_1.jpg', 'Avatar 1'), ('IMAGES/profile_pics/avatar_2.jpg', 'Avatar 2'), ('IMAGES/profile_pics/avatar_3.jpg', 'Avatar 3'), ('IMAGES/profile_pics/avatar_4.jpg', 'Avatar 4'), ('IMAGES/profile_pics/avatar_5.jpg', 'Avatar 5')], default='No Image', upload_to='profile_pics'),
        ),
    ]
