# Generated by Django 3.0.3 on 2020-08-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200802_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(choices=[('IMAGES/profile_pics/no_profile_pic.jpg', 'No Image'), ('IMAGES/profile_pics/avatar_1.jpg', 'Avatar 1'), ('IMAGES/profile_pics/avatar_2.jpg', 'Avatar 2'), ('IMAGES/profile_pics/avatar_3.jpg', 'Avatar 3'), ('IMAGES/profile_pics/avatar_4.jpg', 'Avatar 4'), ('IMAGES/profile_pics/avatar_5.jpg', 'Avatar 5'), ('IMAGES/profile_pics/avatar_6.jpg', 'Avatar 6'), ('IMAGES/profile_pics/avatar_7.jpg', 'Avatar 7'), ('IMAGES/profile_pics/avatar_8.jpg', 'Avatar 8'), ('IMAGES/profile_pics/avatar_9.jpg', 'Avatar 9'), ('IMAGES/profile_pics/avatar_10.jpg', 'Avatar 10')], default='No Image', upload_to='profile_pics'),
        ),
    ]
